name: anewsment
description: "News App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  get: ^4.7.2
  html: ^0.15.6
  http: ^1.4.0
  intl: ^0.20.2
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/screenshots/article_detail_android.png
    - assets/screenshots/article_detail_ios.png
    - assets/screenshots/articles_android.png
    - assets/screenshots/articles_ios.png
    - assets/screenshots/cluster_android.png
    - assets/screenshots/cluster_ios.png
    - assets/screenshots/news_android.png
    - assets/screenshots/news_ios.png
    - assets/screenshots/on_this_day_android.png
    - assets/screenshots/on_this_day_ios.png
    - assets/screenshots/todays_news_android.png
    - assets/screenshots/todays_news_ios.png
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
